CREATE DATABASE IF NOT EXISTS PRATADEIRA;
USE PRATADEIRA;

CREATE TABLE IF NOT EXISTS users (
    id_users INT AUTO_INCREMENT PRIMARY KEY,
    nome_users VARCHAR(50) NOT NULL,
    email_users VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS pratos (
    id_pratos INT AUTO_INCREMENT PRIMARY KEY,
    nome_pratos VARCHAR(50) NOT NULL,
    descricao_pratos VARCHAR(100) NOT NULL,
    preco_pratos VARCHAR(100) NOT NULL,
    categoria_pratos VARCHAR(100) NOT NULL,
    nome_users VARCHAR(50) NOT NULL
);