CREATE DATABASE IF NOT EXISTS PRATADEIRA;
USE PRATADEIRA;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS pratos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    descrição VARCHAR(100) NOT NULL,
    preco VARCHAR(100) NOT NULL,
    categoria VARCHAR(100) NOT NULL
);